CREATE DATABASE ComedoresComunitarios;
GO

USE ComedoresComunitarios;
GO

DROP TABLE IF EXISTS Comensal;
CREATE TABLE Comensal(
	IDComensal INT AUTO_INCREMENT,
	CURP VARCHAR(18) NOT NULL,
	Nombre VARCHAR(50) NOT NULL,
	Apellido VARCHAR(100) NOT NULL, 
	Fecha DATE NOT NULL,
	Genero VARCHAR(10),
	Pass VARCHAR(80) NOT NULL,
	PRIMARY KEY (IDComensal)
);
GO

DROP TABLE IF EXISTS Responsable;
CREATE TABLE Responsable(
	IDResponsable INT AUTO_INCREMENT,
	CURP VARCHAR(18) NOT NULL UNIQUE,
	Nombre VARCHAR(50) NOT NULL,
	Pass VARCHAR(80) NOT NULL,
	Estado VARCHAR(20) NOT NULL,
	PRIMARY KEY (IDResponsable)
);
GO

DROP TABLE IF EXISTS AdministradorDIF;
CREATE TABLE AdministradorDIF(
	IDAdministrador INT AUTO_INCREMENT,
	Usuario VARCHAR(50) NOT NULL,
	Pass VARCHAR(80) NOT NULL,
	PRIMARY KEY (IDAdministrador)
);
GO

DROP TABLE IF EXISTS Afeccion;
CREATE TABLE Afeccion(
	IDAfeccion INT AUTO_INCREMENT,
	Tipo VARCHAR(50) NOT NULL, 
	PRIMARY KEY (IDAfeccion)
);
GO

DROP TABLE IF EXISTS Comedor;
CREATE TABLE Comedor(
	IDComedor INT AUTO_INCREMENT,
	Ubicacion VARCHAR(200) NOT NULL,
	Fecha DATE NOT NULL,
	Estado VARCHAR(20) NOT NULL,
	IDResponsable INT NOT NULL,
	CONSTRAINT FK_Comedor_RESPONSABLE FOREIGN KEY (IDResponsable)
	REFERENCES Responsable(IDResponsable)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION,
	PRIMARY KEY(IDComedor)
);
GO

DROP TABLE IF EXISTS ComensalAfeccion;
CREATE TABLE ComensalAfeccion(
	IDComensal INT NOT NULL,
	CONSTRAINT FK_ComensalAfeccion_COMENSAL FOREIGN KEY (IDComensal)
	REFERENCES Comensal(IDComensal)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION,
	IDAfeccion INT NOT NULL,
	CONSTRAINT FK_ComensalAfeccion_AFECCION FOREIGN KEY (IDAfeccion)
	REFERENCES Afeccion(IDAfeccion)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
);
GO

DROP TABLE IF EXISTS ComedorComensal;
CREATE TABLE ComedorComensal(
	IDComensal INT NOT NULL, 
	CONSTRAINT FK_ComedorComensal_IDCOMENSAL FOREIGN KEY (IDComensal)
	REFERENCES Comensal(IDComensal)
	ON UPDATE NO ACTION 
	ON DELETE NO ACTION,
	IDComedor INT NOT NULL,
	CONSTRAINT FK_ComedorComensal_IDCOMEDOR FOREIGN KEY (IDComedor)
	REFERENCES Comedor(IDComedor)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION,
	Pago INT NOT NULL,
	Fecha DATE NOT NULL,
	Lugar VARCHAR(100) NOT NULL
);
GO

DROP TABLE IF EXISTS RacionDonada;
CREATE TABLE RacionDonada(
	IDComedor INT NOT NULL,
	CONSTRAINT FK_RacionDonada_COMEDOR FOREIGN KEY (IDComedor)
	REFERENCES Comedor(IDComedor)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION,
	IDComensal INT NOT NULL,
	CONSTRAINT FK_RacionDonada_COMENSAL FOREIGN KEY (IDComensal)
	REFERENCES Comensal(IDComensal)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION,
	Fecha DATE
);
GO

DROP TABLE IF EXISTS Producto;
CREATE TABLE Producto(
	IDProducto INT AUTO_INCREMENT,
	Nombre VARCHAR(50) NOT NULL,
	Presentacion VARCHAR(50) NOT NULL,
	PRIMARY KEY(IDProducto)
);
GO

DROP TABLE IF EXISTS Inventario;
CREATE TABLE Inventario(
	IDComedor INT NOT NULL,
	CONSTRAINT FK_Inventario_COMEDOR FOREIGN KEY (IDComedor)
	REFERENCES Comedor(IDComedor)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION,
	IDProducto INT NOT NULL,
	CONSTRAINT FK_Inventario_PRODUCTO FOREIGN KEY (IDProducto)
	REFERENCES Producto(IDProducto)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION,
	Cantidad INT NOT NULL
);
GO

DROP TABLE IF EXISTS Encuesta;
CREATE TABLE Encuesta(
	IDEncuesta INT AUTO_INCREMENT,
	IDComedor INT NOT NULL,
	CONSTRAINT FK_Encuesta_COMEDOR FOREIGN KEY (IDComedor)
	REFERENCES Comedor(IDComedor)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION,
	Calidad INT NOT NULL,
	Higiene INT NOT NULL,
	Servicio INT NOT NULL,
	Comentario VARCHAR(200),
	Fecha DATE NOT NULL,
	PRIMARY KEY (IDEncuesta)
);

DROP TABLE IF EXISTS Incidente;
CREATE TABLE Incidente(
	IDIncidente INT AUTO_INCREMENT,
	IDResponsable INT NOT NULL,
	CONSTRAINT FK_Comedor_RESPONSA FOREIGN KEY (IDResponsable)
	REFERENCES Responsable (IDResponsable)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION,
	Incidente VARCHAR(200),
	Fecha DATE NOT NULL,
	PRIMARY KEY (IDIncidente)
);

DROP TABLE IF EXISTS Avisos;
CREATE TABLE Avisos(
	IDAviso INT AUTO_INCREMENT,
	IDComedor INT NOT NULL,
	CONSTRAINT FK_Avisos FOREIGN KEY (IDComedor)
	REFERENCES Comedor (IDComedor)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION,
	Aviso VARCHAR (250),
	Fecha DATE,
	PRIMARY KEY (IDAviso)
);




	

